export interface Theme {
  name: string;
  label: string;
  colors: Record<string, string>;
}

export const THEMES: Theme[] = [
  {
    name: "parchment",
    label: "Parchment",
    colors: {
      "--color-bg": "#f4f0e8",
      "--color-surface": "#ebe5d9",
      "--color-panel": "#faf8f3",
      "--color-panel-alt": "#f0ece3",
      "--color-panel-active": "#e4dfd4",
      "--color-border": "#c8c1b0",
      "--color-border-subtle": "#d6d0c3",
      "--color-border-strong": "#a8b5a0",
      "--color-text": "#1a1f17",
      "--color-text-muted": "#6b7265",
      "--color-accent": "#2d6a4f",
      "--color-accent-soft": "#d8e2dc",
    },
  },
  {
    name: "dark",
    label: "Dark",
    colors: {
      "--color-bg": "#1e1e1e",
      "--color-surface": "#252526",
      "--color-panel": "#2d2d2d",
      "--color-panel-alt": "#333333",
      "--color-panel-active": "#3c3c3c",
      "--color-border": "#404040",
      "--color-border-subtle": "#353535",
      "--color-border-strong": "#505050",
      "--color-text": "#d4d4d4",
      "--color-text-muted": "#808080",
      "--color-accent": "#4ec9b0",
      "--color-accent-soft": "#2d4a44",
    },
  },
  {
    name: "nord",
    label: "Nord",
    colors: {
      "--color-bg": "#2e3440",
      "--color-surface": "#3b4252",
      "--color-panel": "#434c5e",
      "--color-panel-alt": "#4c566a",
      "--color-panel-active": "#4c566a",
      "--color-border": "#4c566a",
      "--color-border-subtle": "#434c5e",
      "--color-border-strong": "#d8dee9",
      "--color-text": "#eceff4",
      "--color-text-muted": "#81a1c1",
      "--color-accent": "#88c0d0",
      "--color-accent-soft": "#3b4a5a",
    },
  },
  {
    name: "dracula",
    label: "Dracula",
    colors: {
      "--color-bg": "#282a36",
      "--color-surface": "#21222c",
      "--color-panel": "#343746",
      "--color-panel-alt": "#3e4152",
      "--color-panel-active": "#44475a",
      "--color-border": "#44475a",
      "--color-border-subtle": "#383a4a",
      "--color-border-strong": "#6272a4",
      "--color-text": "#f8f8f2",
      "--color-text-muted": "#6272a4",
      "--color-accent": "#bd93f9",
      "--color-accent-soft": "#3d3566",
    },
  },
  {
    name: "solarized",
    label: "Solarized Light",
    colors: {
      "--color-bg": "#fdf6e3",
      "--color-surface": "#eee8d5",
      "--color-panel": "#fdf6e3",
      "--color-panel-alt": "#eee8d5",
      "--color-panel-active": "#e0dbc8",
      "--color-border": "#d0c8b0",
      "--color-border-subtle": "#ddd6c1",
      "--color-border-strong": "#93a1a1",
      "--color-text": "#073642",
      "--color-text-muted": "#586e75",
      "--color-accent": "#268bd2",
      "--color-accent-soft": "#d5e8f0",
    },
  },
  {
    name: "claude",
    label: "Claude",
    colors: {
      "--color-bg": "#f7f3eb",
      "--color-surface": "#efe9dd",
      "--color-panel": "#fcfaf6",
      "--color-panel-alt": "#f2ece0",
      "--color-panel-active": "#e7dfd1",
      "--color-border": "#d4c9b5",
      "--color-border-subtle": "#e0d8c8",
      "--color-border-strong": "#c4a882",
      "--color-text": "#2d2418",
      "--color-text-muted": "#8c7b66",
      "--color-accent": "#da7e37",
      "--color-accent-soft": "#f5e6d4",
      "--color-teal": "#da7e37",
      "--color-coral": "#c4533b",
      "--color-amber": "#b8860b",
      "--color-focus-ring": "#da7e3740",
    },
  },
  {
    name: "sakura",
    label: "Sakura",
    colors: {
      "--color-bg": "#fef5f7",
      "--color-surface": "#fce8ed",
      "--color-panel": "#fff9fa",
      "--color-panel-alt": "#faeef1",
      "--color-panel-active": "#f5dce2",
      "--color-border": "#e8c4cc",
      "--color-border-subtle": "#f0d4db",
      "--color-border-strong": "#d4949e",
      "--color-text": "#3d1f28",
      "--color-text-muted": "#8c6b74",
      "--color-accent": "#c2506a",
      "--color-accent-soft": "#fce0e8",
      "--color-teal": "#c2506a",
      "--color-coral": "#c94040",
      "--color-amber": "#b07834",
      "--color-focus-ring": "#c2506a40",
    },
  },
];
